<a href="https://colab.research.google.com/github/Tusk9/gradprojects/blob/main/NetworkAnalysis6110_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

from IPython.core.display import display, HTML
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.io as pio


import seaborn as sns
from importlib import reload
import matplotlib.pyplot as plt
import matplotlib
import warnings

# Configure Jupyter Notebook
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 500)
pd.set_option('display.expand_frame_repr', False)
# pd.set_option('max_colwidth', -1)
display(HTML("<style>div.output_scroll { height: 35em; }</style>"))

reload(plt)
%matplotlib inline
%config InlineBackend.figure_format ='retina'

warnings.filterwarnings('ignore')

# configure plotly graph objects
pio.renderers.default = 'iframe'
# pio.renderers.default = 'vscode'

pio.templates["ck_template"] = go.layout.Template(
    layout_colorway = px.colors.sequential.Viridis,
#     layout_hovermode = 'closest',
#     layout_hoverdistance = -1,
    layout_autosize=False,
    layout_width=800,
    layout_height=600,
    layout_font = dict(family="Calibri Light"),
    layout_title_font = dict(family="Calibri"),
    layout_hoverlabel_font = dict(family="Calibri Light"),
#     plot_bgcolor="white",
)

# pio.templates.default = 'seaborn+ck_template+gridon'
pio.templates.default = 'ck_template+gridon'
# pio.templates.default = 'seaborn+gridon'
# pio.templates

In [ ]:

df = pd.read_csv("/UNSW_NB15_training-set.csv")
print(df.shape)

(82332, 45)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82332 entries, 0 to 82331
Data columns (total 45 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 82332 non-null  int64
 1   dur                82332 non-null  float64
 2   proto              82332 non-null  object
 3   service            82332 non-null  object
 4   state              82332 non-null  object
 5   spkts              82332 non-null  int64
 6   dpkts              82332 non-null  int64
 7   sbytes             82332 non-null  int64
 8   dbytes             82332 non-null  int64
 9   rate               82332 non-null  float64
 10  sttl               82332 non-null  int64
 11  dttl               82332 non-null  int64
 12  sload              82332 non-null  float64
 13  dload              82332 non-null  float64
 14  sloss              82332 non-null  int64
 15  dloss              82332 non-null  int64
 16  sinpkt             82332 non-null  float64
 17  dinpkt             82332 non-null  float64
 18  sjit               82332 non-null  float64
 19  djit               82332 non-null  float64
 20  swin               82332 non-null  int64
 21  stcpb              82332 non-null  int64
 22  dtcpb              82332 non-null  int64
 23  dwin               82332 non-null  int64
 24  tcprtt             82332 non-null  float64
 25  synack             82332 non-null  float64
 26  ackdat             82332 non-null  float64
 27  smean              82332 non-null  int64
 28  dmean              82332 non-null  int64
 29  trans_depth        82332 non-null  int64
 30  response_body_len  82332 non-null  int64
 31  ct_srv_src         82332 non-null  int64
 32  ct_state_ttl       82332 non-null  int64
 33  ct_dst_ltm         82332 non-null  int64
 34  ct_src_dport_ltm   82332 non-null  int64
 35  ct_dst_sport_ltm   82332 non-null  int64
 36  ct_dst_src_ltm     82332 non-null  int64
 37  is_ftp_login       82332 non-null  int64
 38  ct_ftp_cmd         82332 non-null  int64
 39  ct_flw_http_mthd   82332 non-null  int64
 40  ct_src_ltm         82332 non-null  int64
 41  ct_srv_dst         82332 non-null  int64
 42  is_sm_ips_ports    82332 non-null  int64
 43  attack_cat         82332 non-null  object
 44  label              82332 non-null  int64
dtypes: float64(11), int64(30), object(4)
memory usage: 28.3+ MB

In [ ]:
df.head()

   id       dur proto service state  spkts  dpkts  sbytes  dbytes         rate  sttl  dttl        sload  dload  sloss  dloss  sinpkt  dinpkt  sjit  djit  swin  stcpb  dtcpb  dwin  tcprtt  synack  ackdat  smean  dmean  trans_depth  response_body_len  ct_srv_src  ct_state_ttl  ct_dst_ltm  ct_src_dport_ltm  ct_dst_sport_ltm  ct_dst_src_ltm  is_ftp_login  ct_ftp_cmd  ct_flw_http_mthd  ct_src_ltm  ct_srv_dst  is_sm_ips_ports attack_cat  label
0   1  0.000011   udp       -   INT      2      0     496       0   90909.0902   254     0  180363632.0    0.0      0      0   0.011     0.0   0.0   0.0     0      0      0     0     0.0     0.0     0.0    248      0            0                  0           2             2           1                 1                 1               2             0           0                 0           1           2                0     Normal      0
1   2  0.000008   udp       -   INT      2      0    1762       0  125000.0003   254     0  881000000.0    0.0      0      0   0.008     0.0   0.0   0.0     0      0      0     0     0.0     0.0     0.0    881      0            0                  0           2             2           1                 1                 1               2             0           0                 0           1           2                0     Normal      0
2   3  0.000005   udp       -   INT      2      0    1068       0  200000.0051   254     0  854400000.0    0.0      0      0   0.005     0.0   0.0   0.0     0      0      0     0     0.0     0.0     0.0    534      0            0                  0           3             2           1                 1                 1               3             0           0                 0           1           3                0     Normal      0
3   4  0.000006   udp       -   INT      2      0     900       0  166666.6608   254     0  600000000.0    0.0      0      0   0.006     0.0   0.0   0.0     0      0      0     0     0.0     0.0     0.0    450      0            0                  0           3             2           2                 2                 1               3             0           0                 0           2           3                0     Normal      0
4   5  0.000010   udp       -   INT      2      0    2126       0  100000.0025   254     0  850400000.0    0.0      0      0   0.010     0.0   0.0   0.0     0      0      0     0     0.0     0.0     0.0   1063      0            0                  0           3             2           2                 2                 1               3             0           0                 0           2           3                0     Normal      0

In [ ]:
df.describe(include='all')

                  id           dur  proto service  state         spkts         dpkts        sbytes        dbytes          rate          sttl          dttl         sload         dload         sloss         dloss        sinpkt        dinpkt          sjit           djit         swin         stcpb         dtcpb         dwin        tcprtt        synack        ackdat         smean         dmean   trans_depth  response_body_len    ct_srv_src  ct_state_ttl    ct_dst_ltm  ct_src_dport_ltm  ct_dst_sport_ltm  ct_dst_src_ltm  is_ftp_login    ct_ftp_cmd  ct_flw_http_mthd    ct_src_ltm    ct_srv_dst  is_sm_ips_ports attack_cat         label
count   82332.000000  82332.000000  82332   82332  82332  82332.000000  82332.000000  8.233200e+04  8.233200e+04  8.233200e+04  82332.000000  82332.000000  8.233200e+04  8.233200e+04  82332.000000  82332.000000  82332.000000  82332.000000  8.233200e+04   82332.000000  82332.00000  8.233200e+04  8.233200e+04  82332.00000  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000       8.233200e+04  82332.000000  82332.000000  82332.000000      82332.000000      82332.000000    82332.000000  82332.000000  82332.000000      82332.000000  82332.000000  82332.000000     82332.000000      82332  82332.000000
unique           NaN           NaN    131      13      7           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN            NaN          NaN           NaN           NaN          NaN           NaN           NaN           NaN           NaN           NaN           NaN                NaN           NaN           NaN           NaN               NaN               NaN             NaN           NaN           NaN               NaN           NaN           NaN              NaN         10           NaN
top              NaN           NaN    tcp       -    FIN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN            NaN          NaN           NaN           NaN          NaN           NaN           NaN           NaN           NaN           NaN           NaN                NaN           NaN           NaN           NaN               NaN               NaN             NaN           NaN           NaN               NaN           NaN           NaN              NaN     Normal           NaN
freq             NaN           NaN  43095   47153  39339           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN            NaN          NaN           NaN           NaN          NaN           NaN           NaN           NaN           NaN           NaN           NaN                NaN           NaN           NaN           NaN               NaN               NaN             NaN           NaN           NaN               NaN           NaN           NaN              NaN      37000           NaN
mean    41166.500000      1.006756    NaN     NaN    NaN     18.666472     17.545936  7.993908e+03  1.323379e+04  8.241089e+04    180.967667     95.713003  6.454902e+07  6.305470e+05      4.753692      6.308556    755.394301    121.701284  6.363075e+03     535.180430    133.45908  1.084642e+09  1.073465e+09    128.28662      0.055925      0.029256      0.026669    139.528604    116.275069      0.094277       1.595372e+03      9.546604      1.369273      5.744923          4.928898          3.663011        7.456360      0.008284      0.008381          0.129743      6.468360      9.164262         0.011126        NaN      0.550600
std     23767.345519      4.710444    NaN     NaN    NaN    133.916353    115.574086  1.716423e+05  1.514715e+05  1.486204e+05    101.513358    116.667722  1.798618e+08  2.393001e+06     64.649620     55.708021   6182.615732   1292.378499  5.672402e+04    3635.305383    127.35700  1.390860e+09  1.381996e+09    127.49137      0.116022      0.070854      0.055094    208.472063    244.600271      0.542922       3.806697e+04     11.090289      1.067188      8.418112          8.389545          5.915386       11.415191      0.091171      0.092485          0.638683      8.543927     11.121413         0.104891        NaN      0.497436
min         1.000000      0.000000    NaN     NaN    NaN      1.000000      0.000000  2.400000e+01  0.000000e+00  0.000000e+00      0.000000      0.000000  0.000000e+00  0.000000e+00      0.000000      0.000000      0.000000      0.000000  0.000000e+00       0.000000      0.00000  0.000000e+00  0.000000e+00      0.00000      0.000000      0.000000      0.000000     24.000000      0.000000      0.000000       0.000000e+00      1.000000      0.000000      1.000000          1.000000          1.000000        1.000000      0.000000      0.000000          0.000000      1.000000      1.000000         0.000000        NaN      0.000000
25%     20583.750000      0.000008    NaN     NaN    NaN      2.000000      0.000000  1.140000e+02  0.000000e+00  2.860611e+01     62.000000      0.000000  1.120247e+04  0.000000e+00      0.000000      0.000000      0.008000      0.000000  0.000000e+00       0.000000      0.00000  0.000000e+00  0.000000e+00      0.00000      0.000000      0.000000      0.000000     57.000000      0.000000      0.000000       0.000000e+00      2.000000      1.000000      1.000000          1.000000          1.000000        1.000000      0.000000      0.000000          0.000000      1.000000      2.000000         0.000000        NaN      0.000000
50%     41166.500000      0.014138    NaN     NaN    NaN      6.000000      2.000000  5.340000e+02  1.780000e+02  2.650177e+03    254.000000     29.000000  5.770032e+05  2.112951e+03      1.000000      0.000000      0.557929      0.010000  1.762392e+01       0.000000    255.00000  2.788886e+07  2.856975e+07    255.00000      0.000551      0.000441      0.000080     65.000000     44.000000      0.000000       0.000000e+00      5.000000      1.000000      2.000000          1.000000          1.000000        3.000000      0.000000      0.000000          0.000000      3.000000      5.000000         0.000000        NaN      1.000000
75%     61749.250000      0.719360    NaN     NaN    NaN     12.000000     10.000000  1.280000e+03  9.560000e+02  1.111111e+05    254.000000    252.000000  6.514286e+07  1.585808e+04      3.000000      2.000000     63.409444     63.136369  3.219332e+03     128.459914    255.00000  2.171310e+09  2.144205e+09    255.00000      0.105541      0.052596      0.048816    100.000000     87.000000      0.000000       0.000000e+00     11.000000      2.000000      6.000000          4.000000          3.000000        6.000000      0.000000      0.000000          0.000000      7.000000     11.000000         0.000000        NaN      1.000000
max     82332.000000     59.999989    NaN     NaN    NaN  10646.000000  11018.000000  1.435577e+07  1.465753e+07  1.000000e+06    255.000000    253.000000  5.268000e+09  2.082111e+07   5319.000000   5507.000000  60009.992000  57739.240000  1.483831e+06  463199.240100    255.00000  4.294950e+09  4.294881e+09    255.00000      3.821465      3.226788      2.928778   1504.000000   1500.000000    131.000000       5.242880e+06     63.000000      6.000000     59.000000         59.000000         38.000000       63.000000      2.000000      2.000000         16.000000     60.000000     62.000000         1.000000        NaN      1.000000

In [ ]:
list_drop = ['id','attack_cat']

In [ ]:
df.drop(list_drop,axis=1,inplace=True)

In [ ]:
# Clamp extreme Values
df_numeric = df.select_dtypes(include=[np.number])
df_numeric.describe(include='all')

                dur         spkts         dpkts        sbytes        dbytes          rate          sttl          dttl         sload         dload         sloss         dloss        sinpkt        dinpkt          sjit           djit         swin         stcpb         dtcpb         dwin        tcprtt        synack        ackdat         smean         dmean   trans_depth  response_body_len    ct_srv_src  ct_state_ttl    ct_dst_ltm  ct_src_dport_ltm  ct_dst_sport_ltm  ct_dst_src_ltm  is_ftp_login    ct_ftp_cmd  ct_flw_http_mthd    ct_src_ltm    ct_srv_dst  is_sm_ips_ports         label
count  82332.000000  82332.000000  82332.000000  8.233200e+04  8.233200e+04  8.233200e+04  82332.000000  82332.000000  8.233200e+04  8.233200e+04  82332.000000  82332.000000  82332.000000  82332.000000  8.233200e+04   82332.000000  82332.00000  8.233200e+04  8.233200e+04  82332.00000  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000       8.233200e+04  82332.000000  82332.000000  82332.000000      82332.000000      82332.000000    82332.000000  82332.000000  82332.000000      82332.000000  82332.000000  82332.000000     82332.000000  82332.000000
mean       1.006756     18.666472     17.545936  7.993908e+03  1.323379e+04  8.241089e+04    180.967667     95.713003  6.454902e+07  6.305470e+05      4.753692      6.308556    755.394301    121.701284  6.363075e+03     535.180430    133.45908  1.084642e+09  1.073465e+09    128.28662      0.055925      0.029256      0.026669    139.528604    116.275069      0.094277       1.595372e+03      9.546604      1.369273      5.744923          4.928898          3.663011        7.456360      0.008284      0.008381          0.129743      6.468360      9.164262         0.011126      0.550600
std        4.710444    133.916353    115.574086  1.716423e+05  1.514715e+05  1.486204e+05    101.513358    116.667722  1.798618e+08  2.393001e+06     64.649620     55.708021   6182.615732   1292.378499  5.672402e+04    3635.305383    127.35700  1.390860e+09  1.381996e+09    127.49137      0.116022      0.070854      0.055094    208.472063    244.600271      0.542922       3.806697e+04     11.090289      1.067188      8.418112          8.389545          5.915386       11.415191      0.091171      0.092485          0.638683      8.543927     11.121413         0.104891      0.497436
min        0.000000      1.000000      0.000000  2.400000e+01  0.000000e+00  0.000000e+00      0.000000      0.000000  0.000000e+00  0.000000e+00      0.000000      0.000000      0.000000      0.000000  0.000000e+00       0.000000      0.00000  0.000000e+00  0.000000e+00      0.00000      0.000000      0.000000      0.000000     24.000000      0.000000      0.000000       0.000000e+00      1.000000      0.000000      1.000000          1.000000          1.000000        1.000000      0.000000      0.000000          0.000000      1.000000      1.000000         0.000000      0.000000
25%        0.000008      2.000000      0.000000  1.140000e+02  0.000000e+00  2.860611e+01     62.000000      0.000000  1.120247e+04  0.000000e+00      0.000000      0.000000      0.008000      0.000000  0.000000e+00       0.000000      0.00000  0.000000e+00  0.000000e+00      0.00000      0.000000      0.000000      0.000000     57.000000      0.000000      0.000000       0.000000e+00      2.000000      1.000000      1.000000          1.000000          1.000000        1.000000      0.000000      0.000000          0.000000      1.000000      2.000000         0.000000      0.000000
50%        0.014138      6.000000      2.000000  5.340000e+02  1.780000e+02  2.650177e+03    254.000000     29.000000  5.770032e+05  2.112951e+03      1.000000      0.000000      0.557929      0.010000  1.762392e+01       0.000000    255.00000  2.788886e+07  2.856975e+07    255.00000      0.000551      0.000441      0.000080     65.000000     44.000000      0.000000       0.000000e+00      5.000000      1.000000      2.000000          1.000000          1.000000        3.000000      0.000000      0.000000          0.000000      3.000000      5.000000         0.000000      1.000000
75%        0.719360     12.000000     10.000000  1.280000e+03  9.560000e+02  1.111111e+05    254.000000    252.000000  6.514286e+07  1.585808e+04      3.000000      2.000000     63.409444     63.136369  3.219332e+03     128.459914    255.00000  2.171310e+09  2.144205e+09    255.00000      0.105541      0.052596      0.048816    100.000000     87.000000      0.000000       0.000000e+00     11.000000      2.000000      6.000000          4.000000          3.000000        6.000000      0.000000      0.000000          0.000000      7.000000     11.000000         0.000000      1.000000
max       59.999989  10646.000000  11018.000000  1.435577e+07  1.465753e+07  1.000000e+06    255.000000    253.000000  5.268000e+09  2.082111e+07   5319.000000   5507.000000  60009.992000  57739.240000  1.483831e+06  463199.240100    255.00000  4.294950e+09  4.294881e+09    255.00000      3.821465      3.226788      2.928778   1504.000000   1500.000000    131.000000       5.242880e+06     63.000000      6.000000     59.000000         59.000000         38.000000       63.000000      2.000000      2.000000         16.000000     60.000000     62.000000         1.000000      1.000000

In [ ]:
DEBUG =0

for feature in df_numeric.columns:
    if DEBUG == 1:
        print(feature)
        print('max = '+str(df_numeric[feature].max()))
        print('75th = '+str(df_numeric[feature].quantile(0.95)))
        print('median = '+str(df_numeric[feature].median()))
        print(df_numeric[feature].max()>10*df_numeric[feature].median())
        print('----------------------------------------------------')
    if df_numeric[feature].max()>10*df_numeric[feature].median() and df_numeric[feature].max()>10 :
        df[feature] = np.where(df[feature]<df[feature].quantile(0.95), df[feature], df[feature].quantile(0.95))

In [ ]:
#Clamping

df_numeric = df.select_dtypes(include=[np.number])
df_numeric.describe(include='all')

                dur        spkts         dpkts        sbytes        dbytes           rate          sttl          dttl         sload         dload         sloss         dloss        sinpkt        dinpkt          sjit          djit         swin         stcpb         dtcpb         dwin        tcprtt        synack        ackdat         smean         dmean   trans_depth  response_body_len    ct_srv_src  ct_state_ttl    ct_dst_ltm  ct_src_dport_ltm  ct_dst_sport_ltm  ct_dst_src_ltm  is_ftp_login    ct_ftp_cmd  ct_flw_http_mthd    ct_src_ltm    ct_srv_dst  is_sm_ips_ports         label
count  82332.000000  82332.00000  82332.000000  82332.000000  82332.000000   82332.000000  82332.000000  82332.000000  8.233200e+04  8.233200e+04  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000  82332.00000  8.233200e+04  8.233200e+04  82332.00000  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000       82332.000000  82332.000000  82332.000000  82332.000000      82332.000000      82332.000000    82332.000000  82332.000000  82332.000000      82332.000000  82332.000000  82332.000000     82332.000000  82332.000000
mean       0.445016     11.84186      9.178424   1580.566135   2866.918367   71576.702810    180.967667     95.713003  4.649418e+07  3.105380e+05      2.188068      2.542729     37.836042     33.982038   1920.889858    199.566224    133.45908  1.074064e+09  1.062670e+09    128.28662      0.055925      0.029256      0.026669    124.772822    100.240891      0.092091           9.643063      9.259887      1.369273      5.269591          4.466611          3.388901        7.160679      0.008284      0.008381          0.092066      5.974809      8.832532         0.011126      0.550600
std        0.672222     15.66461     14.504212   2948.850472   7525.606738  102631.946851    101.513358    116.667722  7.417784e+07  8.918691e+05      3.057946      4.767511     57.658385     52.184248   2900.509949    520.285264    127.35700  1.368335e+09  1.358850e+09    127.49137      0.116022      0.070854      0.055094    148.294212    184.094183      0.289156          35.977508     10.221752      1.067188      6.729755          6.685037          5.029129       10.481621      0.091171      0.092485          0.289121      6.867156     10.124902         0.104891      0.497436
min        0.000000      1.00000      0.000000     24.000000      0.000000       0.000000      0.000000      0.000000  0.000000e+00  0.000000e+00      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.00000  0.000000e+00  0.000000e+00      0.00000      0.000000      0.000000      0.000000     24.000000      0.000000      0.000000           0.000000      1.000000      0.000000      1.000000          1.000000          1.000000        1.000000      0.000000      0.000000          0.000000      1.000000      1.000000         0.000000      0.000000
25%        0.000008      2.00000      0.000000    114.000000      0.000000      28.606114     62.000000      0.000000  1.120247e+04  0.000000e+00      0.000000      0.000000      0.008000      0.000000      0.000000      0.000000      0.00000  0.000000e+00  0.000000e+00      0.00000      0.000000      0.000000      0.000000     57.000000      0.000000      0.000000           0.000000      2.000000      1.000000      1.000000          1.000000          1.000000        1.000000      0.000000      0.000000          0.000000      1.000000      2.000000         0.000000      0.000000
50%        0.014138      6.00000      2.000000    534.000000    178.000000    2650.176667    254.000000     29.000000  5.770032e+05  2.112951e+03      1.000000      0.000000      0.557929      0.010000     17.623918      0.000000    255.00000  2.788886e+07  2.856975e+07    255.00000      0.000551      0.000441      0.000080     65.000000     44.000000      0.000000           0.000000      5.000000      1.000000      2.000000          1.000000          1.000000        3.000000      0.000000      0.000000          0.000000      3.000000      5.000000         0.000000      1.000000
75%        0.719360     12.00000     10.000000   1280.000000    956.000000  111111.107200    254.000000    252.000000  6.514286e+07  1.585808e+04      3.000000      2.000000     63.409444     63.136369   3219.332412    128.459914    255.00000  2.171310e+09  2.144205e+09    255.00000      0.105541      0.052596      0.048816    100.000000     87.000000      0.000000           0.000000     11.000000      2.000000      6.000000          4.000000          3.000000        6.000000      0.000000      0.000000          0.000000      7.000000     11.000000         0.000000      1.000000
max        2.403792     60.00000     54.000000  12472.000000  30622.000000  333333.321500    255.000000    253.000000  2.666667e+08  3.741446e+06     11.000000     18.000000    204.530258    167.626851   9532.382646   2218.933526    255.00000  3.876194e+09  3.862459e+09    255.00000      3.821465      3.226788      2.928778    638.000000    683.000000      1.000000         150.450000     37.000000      6.000000     25.000000         25.000000         18.000000       37.000000      2.000000      2.000000          1.000000     25.000000     36.000000         1.000000      1.000000

In [ ]:
#apply log
df_numeric = df.select_dtypes(include=[np.number])
df_before = df_numeric.copy()
DEBUG = 0
for feature in df_numeric.columns:
    if DEBUG == 1:
        print(feature)
        print('nunique = '+str(df_numeric[feature].nunique()))
        print(df_numeric[feature].nunique()>50)
        print('----------------------------------------------------')
    if df_numeric[feature].nunique()>50:
        if df_numeric[feature].min()==0:
            df[feature] = np.log(df[feature]+1)
        else:
            df[feature] = np.log(df[feature])

df_numeric = df.select_dtypes(include=[np.number])

In [ ]:
df_cat = df.select_dtypes(exclude=[np.number])
df_cat.describe(include='all')

        proto service  state
count   82332   82332  82332
unique    131      13      7
top       tcp       -    FIN
freq    43095   47153  39339

In [ ]:
DEBUG = 0
for feature in df_cat.columns:
    if DEBUG == 1:
        print(feature)
        print('nunique = '+str(df_cat[feature].nunique()))
        print(df_cat[feature].nunique()>6)
        print(sum(df[feature].isin(df[feature].value_counts().head().index)))
        print('----------------------------------------------------')

    if df_cat[feature].nunique()>6:
        df[feature] = np.where(df[feature].isin(df[feature].value_counts().head().index), df[feature], '-')

In [ ]:
df_numeric = df.select_dtypes(include=[np.number])
df_numeric.describe(include='all')

                dur         spkts         dpkts        sbytes        dbytes          rate          sttl          dttl         sload         dload         sloss         dloss        sinpkt        dinpkt          sjit          djit         swin         stcpb         dtcpb         dwin        tcprtt        synack        ackdat         smean         dmean   trans_depth  response_body_len    ct_srv_src  ct_state_ttl    ct_dst_ltm  ct_src_dport_ltm  ct_dst_sport_ltm  ct_dst_src_ltm  is_ftp_login    ct_ftp_cmd  ct_flw_http_mthd    ct_src_ltm    ct_srv_dst  is_sm_ips_ports         label
count  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000  82332.00000  82332.000000  82332.000000  82332.00000  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000  82332.000000       82332.000000  82332.000000  82332.000000  82332.000000      82332.000000      82332.000000    82332.000000  82332.000000  82332.000000      82332.000000  82332.000000  82332.000000     82332.000000  82332.000000
mean       0.285416      1.774664      1.396991      6.246847      3.938930      7.480228    180.967667     95.713003     13.549943      5.800992      2.188068      2.542729      1.921965      1.720003      3.827732      2.344287    133.45908     10.663554     10.653152    128.28662      0.050094      0.027154      0.025156      4.483776      2.616677      0.092091           0.338792      9.259887      1.369273      5.269591          4.466611          3.388901        7.160679      0.008284      0.008381          0.092066      5.974809      8.832532         0.011126      0.550600
std        0.381427      1.152950      1.385679      1.442026      3.700028      4.099853    101.513358    116.667722      4.501575      5.512759      3.057946      4.767511      2.096859      2.090606      3.911131      2.685818    127.35700     10.613580     10.606607    127.49137      0.087261      0.054236      0.046184      0.694042      2.413983      0.289156           1.248863     10.221752      1.067188      6.729755          6.685037          5.029129       10.481621      0.091171      0.092485          0.289121      6.867156     10.124902         0.104891      0.497436
min        0.000000      0.000000      0.000000      3.178054      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.00000      0.000000      0.000000      0.00000      0.000000      0.000000      0.000000      3.178054      0.000000      0.000000           0.000000      1.000000      0.000000      1.000000          1.000000          1.000000        1.000000      0.000000      0.000000          0.000000      1.000000      1.000000         0.000000      0.000000
25%        0.000008      0.693147      0.000000      4.736198      0.000000      3.387981     62.000000      0.000000      9.323979      0.000000      0.000000      0.000000      0.007968      0.000000      0.000000      0.000000      0.00000      0.000000      0.000000      0.00000      0.000000      0.000000      0.000000      4.043051      0.000000      0.000000           0.000000      2.000000      1.000000      1.000000          1.000000          1.000000        1.000000      0.000000      0.000000          0.000000      1.000000      2.000000         0.000000      0.000000
50%        0.014039      1.791759      1.098612      6.280396      5.187386      7.882759    254.000000     29.000000     13.265605      7.656314      1.000000      0.000000      0.443357      0.009950      2.924447      0.000000    255.00000     17.143737     17.167854    255.00000      0.000551      0.000441      0.000080      4.174387      3.806662      0.000000           0.000000      5.000000      1.000000      2.000000          1.000000          1.000000        3.000000      0.000000      0.000000          0.000000      3.000000      5.000000         0.000000      1.000000
75%        0.541952      2.484907      2.397895      7.154615      6.863803     11.618295    254.000000    252.000000     17.992093      9.671498      3.000000      2.000000      4.165260      4.161012      8.077240      4.863371    255.00000     21.498596     21.486035    255.00000      0.100335      0.051259      0.047662      4.605170      4.477337      0.000000           0.000000     11.000000      2.000000      6.000000          4.000000          3.000000        6.000000      0.000000      0.000000          0.000000      7.000000     11.000000         0.000000      1.000000
max        1.224890      4.094345      4.007333      9.431241     10.329507     12.716901    255.000000    253.000000     19.401510     15.134983     11.000000     18.000000      5.325593      5.127688      9.162555      7.705233    255.00000     22.078120     22.074570    255.00000      1.573078      1.441442      1.368328      6.458338      6.527958      1.000000           5.020256     37.000000      6.000000     25.000000         25.000000         18.000000       37.000000      2.000000      2.000000          1.000000     25.000000     36.000000         1.000000      1.000000

In [ ]:
df['proto'].value_counts().head().index

Index(['tcp', 'udp', '-', 'unas', 'arp'], dtype='object')

In [ ]:
df['proto'].value_counts().index

Index(['tcp', 'udp', '-', 'unas', 'arp', 'ospf'], dtype='object')

In [ ]:
# Feature Selection
from sklearn.feature_selection import SelectKBest, chi2

best_features = SelectKBest(score_func=chi2,k='all')

X = df.iloc[:,4:-2]
y = df.iloc[:,-1]
fit = best_features.fit(X,y)

df_scores=pd.DataFrame(fit.scores_)
df_col=pd.DataFrame(X.columns)

feature_score=pd.concat([df_col,df_scores],axis=1)
feature_score.columns=['feature','score']
feature_score.sort_values(by=['score'],ascending=True,inplace=True)

fig = go.Figure(go.Bar(
            x=feature_score['score'][0:21],
            y=feature_score['feature'][0:21],
            orientation='h'))

fig.update_layout(title="Top 20 Features",
                  height=1200,
                  showlegend=False,
                 )

fig.show()

In [ ]:
# Feature Selection
from sklearn.feature_selection import SelectKBest, chi2

best_features = SelectKBest(score_func=chi2,k='all')

X = df.iloc[:,4:-2]
y = df.iloc[:,-1]
fit = best_features.fit(X,y)

df_scores=pd.DataFrame(fit.scores_)
df_col=pd.DataFrame(X.columns)

feature_score=pd.concat([df_col,df_scores],axis=1)
feature_score.columns=['feature','score']
feature_score.sort_values(by=['score'],ascending=True,inplace=True)

fig = go.Figure(go.Bar(
            x=feature_score['score'][0:21],
            y=feature_score['feature'][0:21],
            orientation='h'))

fig.update_layout(title="Top 20 Features",
                  height=1200,
                  showlegend=False,
                 )

fig.show()

In [ ]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [ ]:
X.head()
feature_names = list(X.columns)
np.shape(X)

(82332, 42)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,2,3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
np.shape(X)

(82332, 56)

In [ ]:
df_cat.describe(include='all')

        proto service  state
count   82332   82332  82332
unique    131      13      7
top       tcp       -    FIN
freq    43095   47153  39339

In [ ]:
X[0]

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
       0.00000000e+00, 1.09999395e-05, 6.93147181e-01, 0.00000000e+00,
       6.20657593e+00, 0.00000000e+00, 1.14176263e+01, 2.54000000e+02,
       0.00000000e+00, 1.90104856e+01, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 1.09399400e-02, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       5.51342875e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       2.00000000e+00, 2.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 2.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 1.00000000e+00, 2.00000000e+00, 0.00000000e+00])

In [ ]:
len(feature_names)

42

In [ ]:
for label in list(df_cat['state'].value_counts().index)[::-1][1:]:
    feature_names.insert(0,label)

for label in list(df_cat['service'].value_counts().index)[::-1][1:]:
    feature_names.insert(0,label)

for label in list(df_cat['proto'].value_counts().index)[::-1][1:]:
    feature_names.insert(0,label)

In [ ]:
len(feature_names)

190

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size = 0.2,
                                                    random_state = 0,
                                                    stratify=y)

In [ ]:
df_cat.describe(include='all')

        proto service  state
count   82332   82332  82332
unique    131      13      7
top       tcp       -    FIN
freq    43095   47153  39339

In [ ]:
# 6 + 5 + 6 unique = 17, therefore the first 17 rows will be the categories that have been encoded, start scaling from row 18 only.

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 18:] = sc.fit_transform(X_train[:, 18:])
X_test[:, 18:] = sc.transform(X_test[:, 18:])

In [ ]:
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score

import time
model_performance = pd.DataFrame(columns=['Accuracy','Recall','Precision','F1-Score','time to train','time to predict','total time'])

In [ ]:
%%time
from sklearn.linear_model import LogisticRegression
start = time.time()
model = LogisticRegression().fit(X_train,y_train)
end_train = time.time()
y_predictions = model.predict(X_test) # These are the predictions from the test data.
end_predict = time.time()

CPU times: user 1.82 s, sys: 764 ms, total: 2.58 s
Wall time: 2.42 s

In [ ]:
accuracy = accuracy_score(y_test, y_predictions)
recall = recall_score(y_test, y_predictions, average='weighted')
precision = precision_score(y_test, y_predictions, average='weighted')
f1s = f1_score(y_test, y_predictions, average='weighted')

print("Accuracy: "+ "{:.2%}".format(accuracy))
print("Recall: "+ "{:.2%}".format(recall))
print("Precision: "+ "{:.2%}".format(precision))
print("F1-Score: "+ "{:.2%}".format(f1s))
print("time to train: "+ "{:.2f}".format(end_train-start)+" s")
print("time to predict: "+"{:.2f}".format(end_predict-end_train)+" s")
print("total: "+"{:.2f}".format(end_predict-start)+" s")
model_performance.loc['Logistic'] = [accuracy, recall, precision, f1s,end_train-start,end_predict-end_train,end_predict-start]

Accuracy: 92.83%
Recall: 92.83%
Precision: 92.87%
F1-Score: 92.84%
time to train: 2.42 s
time to predict: 0.00 s
total: 2.42 s

In [ ]:
#KNN

%%time
from sklearn.neighbors import KNeighborsClassifier
start = time.time()
model = KNeighborsClassifier(n_neighbors=3).fit(X_train,y_train)
end_train = time.time()
y_predictions = model.predict(X_test) # These are the predictions from the test data.
end_predict = time.time()

CPU times: user 15.6 s, sys: 48.3 ms, total: 15.6 s
Wall time: 20 s

In [ ]:
accuracy = accuracy_score(y_test, y_predictions)
recall = recall_score(y_test, y_predictions, average='weighted')
precision = precision_score(y_test, y_predictions, average='weighted')
f1s = f1_score(y_test, y_predictions, average='weighted')

print("Accuracy: "+ "{:.2%}".format(accuracy))
print("Recall: "+ "{:.2%}".format(recall))
print("Precision: "+ "{:.2%}".format(precision))
print("F1-Score: "+ "{:.2%}".format(f1s))
print("time to train: "+ "{:.2f}".format(end_train-start)+" s")
print("time to predict: "+"{:.2f}".format(end_predict-end_train)+" s")
print("total: "+"{:.2f}".format(end_predict-start)+" s")
model_performance.loc['kNN'] = [accuracy, recall, precision, f1s,end_train-start,end_predict-end_train,end_predict-start]

Accuracy: 95.04%
Recall: 95.04%
Precision: 95.09%
F1-Score: 95.05%
time to train: 0.01 s
time to predict: 19.98 s
total: 19.99 s

In [ ]:
#Decision Tree

%%time
from sklearn.tree import DecisionTreeClassifier
start = time.time()
model = DecisionTreeClassifier().fit(X_train,y_train)
end_train = time.time()
y_predictions = model.predict(X_test) # These are the predictions from the test data.
end_predict = time.time()

CPU times: user 1.74 s, sys: 11.4 ms, total: 1.75 s
Wall time: 3.37 s

In [ ]:
accuracy = accuracy_score(y_test, y_predictions)
recall = recall_score(y_test, y_predictions, average='weighted')
precision = precision_score(y_test, y_predictions, average='weighted')
f1s = f1_score(y_test, y_predictions, average='weighted')

print("Accuracy: "+ "{:.2%}".format(accuracy))
print("Recall: "+ "{:.2%}".format(recall))
print("Precision: "+ "{:.2%}".format(precision))
print("F1-Score: "+ "{:.2%}".format(f1s))
print("time to train: "+ "{:.2f}".format(end_train-start)+" s")
print("time to predict: "+"{:.2f}".format(end_predict-end_train)+" s")
print("total: "+"{:.2f}".format(end_predict-start)+" s")
model_performance.loc['Decision Tree'] = [accuracy, recall, precision, f1s,end_train-start,end_predict-end_train,end_predict-start]

Accuracy: 96.59%
Recall: 96.59%
Precision: 96.59%
F1-Score: 96.59%
time to train: 3.32 s
time to predict: 0.00 s
total: 3.32 s

In [ ]:
#Extra Trees

%%time
from sklearn.ensemble import ExtraTreesClassifier
start = time.time()
model = ExtraTreesClassifier(random_state=0,n_jobs=-1).fit(X_train,y_train)
end_train = time.time()
y_predictions = model.predict(X_test) # These are the predictions from the test data.
end_predict = time.time()

CPU times: user 11.2 s, sys: 115 ms, total: 11.3 s
Wall time: 12.2 s

In [ ]:
accuracy = accuracy_score(y_test, y_predictions)
recall = recall_score(y_test, y_predictions, average='weighted')
precision = precision_score(y_test, y_predictions, average='weighted')
f1s = f1_score(y_test, y_predictions, average='weighted')

print("Accuracy: "+ "{:.2%}".format(accuracy))
print("Recall: "+ "{:.2%}".format(recall))
print("Precision: "+ "{:.2%}".format(precision))
print("F1-Score: "+ "{:.2%}".format(f1s))
print("time to train: "+ "{:.2f}".format(end_train-start)+" s")
print("time to predict: "+"{:.2f}".format(end_predict-end_train)+" s")
print("total: "+"{:.2f}".format(end_predict-start)+" s")
model_performance.loc['Extra Trees'] = [accuracy, recall, precision, f1s,end_train-start,end_predict-end_train,end_predict-start]

Accuracy: 97.53%
Recall: 97.53%
Precision: 97.55%
F1-Score: 97.53%
time to train: 11.90 s
time to predict: 0.25 s
total: 12.15 s

In [ ]:
#Random Forst

%%time
from sklearn.ensemble import RandomForestClassifier
start = time.time()
model = RandomForestClassifier(n_estimators = 100,n_jobs=-1,random_state=0,bootstrap=True,).fit(X_train,y_train)
end_train = time.time()
y_predictions = model.predict(X_test) # These are the predictions from the test data.
end_predict = time.time()

CPU times: user 17.5 s, sys: 97.5 ms, total: 17.6 s
Wall time: 10.4 s

In [ ]:
accuracy = accuracy_score(y_test, y_predictions)
recall = recall_score(y_test, y_predictions, average='weighted')
precision = precision_score(y_test, y_predictions, average='weighted')
f1s = f1_score(y_test, y_predictions, average='weighted')

print("Accuracy: "+ "{:.2%}".format(accuracy))
print("Recall: "+ "{:.2%}".format(recall))
print("Precision: "+ "{:.2%}".format(precision))
print("F1-Score: "+ "{:.2%}".format(f1s))
print("time to train: "+ "{:.2f}".format(end_train-start)+" s")
print("time to predict: "+"{:.2f}".format(end_predict-end_train)+" s")
print("total: "+"{:.2f}".format(end_predict-start)+" s")
model_performance.loc['Random Forest'] = [accuracy, recall, precision, f1s,end_train-start,end_predict-end_train,end_predict-start]

Accuracy: 97.68%
Recall: 97.68%
Precision: 97.69%
F1-Score: 97.68%
time to train: 10.25 s
time to predict: 0.18 s
total: 10.43 s

In [ ]:
#Gradient Boosting

%%time
from sklearn.ensemble import GradientBoostingClassifier
start = time.time()
model = GradientBoostingClassifier().fit(X_train,y_train)
end_train = time.time()
y_predictions = model.predict(X_test) # These are the predictions from the test data.
end_predict = time.time()

CPU times: user 44 s, sys: 54.8 ms, total: 44.1 s
Wall time: 44.2 s

In [ ]:
accuracy = accuracy_score(y_test, y_predictions)
recall = recall_score(y_test, y_predictions, average='weighted')
precision = precision_score(y_test, y_predictions, average='weighted')
f1s = f1_score(y_test, y_predictions, average='weighted')

print("Accuracy: "+ "{:.2%}".format(accuracy))
print("Recall: "+ "{:.2%}".format(recall))
print("Precision: "+ "{:.2%}".format(precision))
print("F1-Score: "+ "{:.2%}".format(f1s))
print("time to train: "+ "{:.2f}".format(end_train-start)+" s")
print("time to predict: "+"{:.2f}".format(end_predict-end_train)+" s")
print("total: "+"{:.2f}".format(end_predict-start)+" s")
model_performance.loc['Gradient Boosting Classifier'] = [accuracy, recall, precision, f1s,end_train-start,end_predict-end_train,end_predict-start]

Accuracy: 95.85%
Recall: 95.85%
Precision: 95.86%
F1-Score: 95.85%
time to train: 44.16 s
time to predict: 0.04 s
total: 44.20 s

In [ ]:
#MLP

%%time
from sklearn.neural_network import MLPClassifier
start = time.time()
model = MLPClassifier(hidden_layer_sizes = (20,20,),
                      activation='relu',
                      solver='adam',
                      batch_size=2000,
                      verbose=0).fit(X_train,y_train)
end_train = time.time()
y_predictions = model.predict(X_test) # These are the predictions from the test data.
end_predict = time.time()

CPU times: user 43.6 s, sys: 23.2 s, total: 1min 6s
Wall time: 39.8 s

In [ ]:
accuracy = accuracy_score(y_test, y_predictions)
recall = recall_score(y_test, y_predictions, average='weighted')
precision = precision_score(y_test, y_predictions, average='weighted')
f1s = f1_score(y_test, y_predictions, average='weighted')

print("Accuracy: "+ "{:.2%}".format(accuracy))
print("Recall: "+ "{:.2%}".format(recall))
print("Precision: "+ "{:.2%}".format(precision))
print("F1-Score: "+ "{:.2%}".format(f1s))
print("time to train: "+ "{:.2f}".format(end_train-start)+" s")
print("time to predict: "+"{:.2f}".format(end_predict-end_train)+" s")
print("total: "+"{:.2f}".format(end_predict-start)+" s")
model_performance.loc['MLP'] = [accuracy, recall, precision, f1s,end_train-start,end_predict-end_train,end_predict-start]

Accuracy: 96.25%
Recall: 96.25%
Precision: 96.30%
F1-Score: 96.25%
time to train: 39.79 s
time to predict: 0.01 s
total: 39.81 s

In [ ]:
model_performance.style.background_gradient(cmap='coolwarm').format({'Accuracy': '{:.2%}',
                                                                     'Precision': '{:.2%}',
                                                                     'Recall': '{:.2%}',
                                                                     'F1-Score': '{:.2%}',
                                                                     'time to train':'{:.1f}',
                                                                     'time to predict':'{:.1f}',
                                                                     'total time':'{:.1f}',
                                                                     })